//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public UserData()
        {
            this.Logins = new HashSet<Login>();
            this.Orders = new HashSet<Order>();
        }
    
        public System.Guid PK { get; set; }
        public string Name { get; set; }
        public string H_TEL { get; set; }
        public string M_TEL { get; set; }
        public string ADDR { get; set; }
        public string EMAIL { get; set; }
        public bool IsEmployee { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
